backend/drm: Fix up tearing for atomic modesetting
labwc/labwc pull request #1996
Opened 2024-07-18 00:14 UTC by kode54

Remove the NO_ATOMIC check, and add a conditional fallback for errors, which usually result from properties being applied during a flip, such as hardware cursor image changes. Falling back is limited so that persistent errors do not keep immediate flips running forever, but instead disable them until an output is reset. Verified working at least on AMD Radeon 6700 XT.

2024-07-18 00:44 UTC, Consolatis commented on src/output.c
> +			&output->pending) && output->pending.tearing_page_flip) {
Second line of the if condition should be double indented to stand out from the code below.

2024-07-18 00:45 UTC, Consolatis commented on src/output.c
> +		}
Could written as
```c
} else if (output->pending.tearing_page_flip) {
	output->tearing_fail_count = 0;
}

2024-07-18 02:20 UTC, Consolatis commented
Thanks for the PR.

LGTM, not tested.
Not merging right away to allow for further feedback.

2024-07-18 03:09 UTC, ahesford requested changes
I don't think we should expose a new configuration option for this. It's awkward, confusing, and will be obsolete whenever we (or wlroots, or whoever is the authority here) considers tearing allowance with atomic modesetting non-experimental. At best, we should note in the manual page (and perhaps in a comment in rc.xml.all) that enabling this option without setting `WLR_DRM_NO_ATOMIC` is experimental and not yet recommended for "production". That has the added benefit of simplifying the code, because we can drop the checks entirely instead of gating them behind another option. (Alternatively, we can log a warning if `WLR_DRM_NO_ATOMIC` is not set when tearing is enabled, and then remove the warning at some point in the future.)

2024-07-18 03:09 UTC, ahesford commented on src/output.c
> +		}
I think restructing this makes the logic a bit easier to read through (the setting of `scene_output` could be moved further up and used in the sanity check at the top of the function):
```suggestion
		struct wlr_scene_output *scene_output = output->scene_output;
		struct wlr_output_state *pending = &output->pending;
		
		bool committed =
			lab_wlr_scene_output_commit(scene_output, pending);
		
		if (!pending->tearing_page_flip) {
			return;
		}
		
		if (committed) {
			output->tearing_fail_count = 0;
		} else {
			if (++output->tearing_fail_count >= TEARING_FAIL_LIMIT) {
				wlr_log(WLR_INFO, "setting tearing allowance failed "
					"for %u consecutive frames, disabling",
					(unsigned int)TEARING_FAIL_LIMIT);
			}
			pending->tearing_page_flip = false;
			lab_wlr_scene_output_commit(scene_output, pending);
		}
```

2024-07-20 03:05 UTC, ahesford requested changes
I think this is looking good. With a nitpick and some trivial documentation cleanup, I think this will be ready to go.

2024-07-20 03:05 UTC, ahesford commented on docs/labwc-config.5.scd
>  	*yes* allow tearing if requested by the active window.
It seems the existing description was not properly edited when we added it. Please drop the final sentence, and maybe we can refine the description for clarity:

    Allow tearing, if requested by the active window, to reduce input lag.
    Default is no.
    
    Note: enabling this option with atomic mode setting is experimental. If
    you experience undesirable side effects when tearing is allowed,
    consider setting the environment variable WLR_DRM_NO_ATOMIC=1 when
    launching labwc.

2024-07-20 03:05 UTC, ahesford commented on src/output.c
> +	return refresh ? refresh / 500 : 120;
In the interest of Postel's law:
```suggestion
	return refresh > 0 ? refresh / 500 : 120;
```

2024-07-20 12:08 UTC, ahesford approved these changes

2024-07-20 12:09 UTC, merged

2024-07-20 12:11 UTC, ahesford commented
Thanks!