Change "FocusOutput" to be more in-line with "MoveToOutput"
labwc/labwc pull request #2100
Opened 2024-08-21 05:00 UTC by orfeasxyz

This is a small patch to address https://github.com/labwc/labwc/issues/2099.

2024-08-21 17:59 UTC, ahesford requested changes
Conceptually, I think it would be good to mimic the `MoveToOutput` behavior here, but there is far too much redundancy. The function `output_get_adjacent_output` (which I might call `output_get_adjacent` for brevity) is essentially identical to `view_get_adjacent_output` except for the latter using `view->output` to grab the output. The function `view_get_adjacent_output` should be eliminated in favor of a common function in `src/action.c` that unifies the output selection before calling `desktop_focus_output` or `view_move_to_output`, depending on the action.

Likewise, the `get_wlr_direction` and `opposite_direction` functions from `view.c` should be made public (and probably relocated into `src/common`) for use without duplication. The names of the functions should be made a bit more descriptive when exposing them publicly. (There is similar duplication of `get_wlr_direction` in `src/overlay.c`, but that is slightly different because it aliases `VIEW_EDGE_CENTER` to `WLR_DIRECTION_UP` rather than throwing an error. This is the version you copied here, but you should instead be using the version from `src/view.c`. I'm not sure if we  still need the unique handling in `src/overlay.c`, but we can keep a separate static function if we do.)

Finally, the configuration parsing for both the `MoveToOutput` and `FocusOutput` actions can be deduplicated.

2024-08-21 21:53 UTC, orfeasxyz commented
> Conceptually, I think it would be good to mimic the `MoveToOutput` behavior here, but there is far too much redundancy. The function `output_get_adjacent_output` (which I might call `output_get_adjacent` for brevity) is essentially identical to `view_get_adjacent_output` except for the latter using `view->output` to grab the output. The function `view_get_adjacent_output` should be eliminated in favor of a common function in `src/action.c` that unifies the output selection before calling `desktop_focus_output` or `view_move_to_output`, depending on the action.
> 
> Likewise, the `get_wlr_direction` and `opposite_direction` functions from `view.c` should be made public (and probably relocated into `src/common`) for use without duplication. The names of the functions should be made a bit more descriptive when exposing them publicly. (There is similar duplication of `get_wlr_direction` in `src/overlay.c`, but that is slightly different because it aliases `VIEW_EDGE_CENTER` to `WLR_DIRECTION_UP` rather than throwing an error. This is the version you copied here, but you should instead be using the version from `src/view.c`. I'm not sure if we still need the unique handling in `src/overlay.c`, but we can keep a separate static function if we do.)
> 
> Finally, the configuration parsing for both the `MoveToOutput` and `FocusOutput` actions can be deduplicated.

I rewrote the patch following your suggestions.

2024-08-23 02:25 UTC, ahesford requested changes
This is looking a lot better, but I have a few more refinements to recommend.

2024-08-23 02:25 UTC, ahesford commented on src/output.c
> +	assert(output);
If we let output be NULL, we can use `output_get_adjacent` as a full replacement for `view_get_adjacent_output` and just kill that function entirely:
```suggestion
	if (!output) {
		output = output_nearest_to_cursor(server);
	}
	
	if (!output_is_usable(output)) {
		wlr_log(WLR_ERROR,
			"output is not usable, cannot find adjacent output");
		return NULL;
	}
```

2024-08-23 02:25 UTC, ahesford commented on src/action.c
> +				desktop_focus_output(target);
With the change to `output_get_adjacent` suggested below, the entire block for this action (except for the final call to `desktop_focus_output(target)` can be wrapped in a static function in this file, something like
```c
static struct output *
adjacent_output(struct output *output, struct server *server, struct action *action)
{
	const char *output_name = action_get_str(action, "output", NULL);
	struct output *target = NULL;
	if (output_name) {
		target = output_from_name(server, output_name);
	} else {
		enum view_edge edge =
			action_get_int(action, "direction", VIEW_EDGE_INVALID);
		bool wrap = action_get_bool(action, "wrap", false);
		target = output_get_adjacent(output, edge, wrap);
	}

	if (!target) {
		wlr_log(WLR_DEBUG, "Invalid output");
	}

	return target;
}
```

Then, this action can just do
```c
struct output *target = adjacent_output(NULL, server, action);
if (target) {
	desktop_focus_output(target);
}
break;
```
while the `ACTION_TYPE_MOVE_TO_OUTPUT` block can just do
```c
if (!view) {
	break;
}
struct output *target = adjacent_output(NULL, server, action);
if (target) {
	view_move_to_output(view, target);
}
break;
```

2024-08-23 13:39 UTC, orfeasxyz commented
I did another set of changes as per suggestion.

2024-08-23 14:43 UTC, ahesford requested changes
With a few tweaks to satisfy the linter, this looks pretty good to me.

2024-08-23 14:43 UTC, ahesford commented on include/labwc.h
> +								   enum view_edge edge, bool wrap);
```suggestion
/**
 * output_get_adjacent() - get next output, in a given direction, from a given output
 * @output: reference output
 * @edge: direction in which to look for the nearest output
 * @wrap: if true, wrap around at layout edge
 *
 * Note: if output is NULL, the output nearest the cursor will be used as the reference.
 */
struct output *output_get_adjacent(struct server *server,
	struct output *output, enum view_edge edge, bool wrap);
```

2024-08-23 14:43 UTC, ahesford commented on include/common/direction.h
> +#ifndef LABWC_DIRECTION_H
```suggestion
// SPDX-License-Identifier: GPL-2.0-only
#ifndef LABWC_DIRECTION_H
```

2024-08-23 14:43 UTC, ahesford commented on src/common/direction.c
> +#include <assert.h>
```suggestion
// SPDX-License-Identifier: GPL-2.0-only
#include <assert.h>
```

2024-08-23 15:59 UTC, orfeasxyz commented
If everything looks ok then we can merge it. Also, thank you a lot for your suggestions.

2024-08-24 15:30 UTC, orfeasxyz commented
I made the final adjustments but the CodeStyleCheck keeps failing, is this a problem with the indentation?

2024-08-24 16:45 UTC, ahesford commented
It seems I led you astray... the license style in the headers should use `/* ... */` comments, while the style in the source files should use `//` comments.

I made this change, along with a couple of other cleanups. (I think your changes broke `view_get_adjacent_output`, and it's obsolete anyway, so I killed it.) Everything should work as expected now. Please take a look at my changes, test that `FocusOutput` and `MoveToOutput` both behave as expected, and I'll squash and merge if you are happy.

2024-08-24 17:32 UTC, orfeasxyz commented
With some quick testing everything seems to be working fine. I think we can go ahead and merge.

2024-08-24 18:59 UTC, merged

2024-08-24 18:59 UTC, ahesford commented
Thanks!